service: vitaliy-sls-test-proj2
frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  environment:
    SQS_QUEUE_URL: { Ref: dataQueue }
    BUCKET_NAME: vitaliy-my-csvs-to-sqs
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
      Resource: "*"
    - Effect: Allow
      Action:
        - sqs:SendMessage
      Resource: "*"
functions:
  file_handler:
    handler: handler.file_handler
    events:
      - s3:
          bucket: ${self:provider.environment.BUCKET_NAME}
          event: s3:ObjectCreated:*
          rules:
            - suffix: .csv
          existing: true
resources:
  Resources:
    dataQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: dataQueue
    myBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.BUCKET_NAME}
